package com.zwp.simpleboot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import com.zwp.simpleboot.entity.Book;
import com.zwp.simpleboot.entity.BookCriteria;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @SelectProvider(type=BookSqlProvider.class, method="countByExample")
    long countByExample(BookCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BookSqlProvider.class, method="deleteByExample")
    int deleteByExample(BookCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @Insert({
        "insert into book (id, name, ",
        "author, publish, ",
        "pages, price, bookcaseid, ",
        "abled)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{author,jdbcType=VARCHAR}, #{publish,jdbcType=VARCHAR}, ",
        "#{pages,jdbcType=INTEGER}, #{price,jdbcType=REAL}, #{bookcaseid,jdbcType=INTEGER}, ",
        "#{abled,jdbcType=INTEGER})"
    })
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @InsertProvider(type=BookSqlProvider.class, method="insertSelective")
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @SelectProvider(type=BookSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish", property="publish", jdbcType=JdbcType.VARCHAR),
        @Result(column="pages", property="pages", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.REAL),
        @Result(column="bookcaseid", property="bookcaseid", jdbcType=JdbcType.INTEGER),
        @Result(column="abled", property="abled", jdbcType=JdbcType.INTEGER)
    })
    List<Book> selectByExample(BookCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BookSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BookSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Book record, @Param("example") BookCriteria example);
}